[
    {
        APPLYFOR:19.5,
        AbsentAll:11,
        Late:0,
        LeaveEarly:0,
        PunchCard:[
            {
                DateStr:"2017-08-01",
                vacation:true,
                type:[
                    {
                        status:false,
                        type:'出勤',
                        time:[
                            ['08:00-09:00',"11:00-12:00"]
                        ]
                    }
                ]
            },
            {
                DateStr:"2017-08-01",
                startDate:'08:55',
                endDate:'20:00',
                vacation:true,
                type:[
                    {
                        status:false,
                        type:'事假',
                        time:[
                            ['08:00-09:00',"11:00-12:00"]
                        ]
                    }
                ]
            }
        ]
    }
]